export const name = "Main Card Game"
export const menu = "Main"
export const edition = "Main Deck"
export const suggestedPlayer = "2-6 players"
export const color = {
  main:  '#c10016',
  contrastText: '#ffffff',
}
export const levels = ['Level 1 Perception', 'Level 2 Connection', 'Level 3 Reflection', 'Final Card']
export const isExpansion = true

export const level1 = [
  "What was your first impression of me?",
  "What do you think is the hardest part of what I do for a living?",
  "What reality show do you think I'm most likely to binge watch? Explain.",
  "What does my style tell you about me?",
  "Do I seem like a cat or dog person?",
  "Do I seem like more of a creative type or analytical type? Explain.",
  "How many speeding tickets do you think I've gotten in my life?",
  "Do I seem like someone who would get a name tattooed on myself? Why or why not?",
  "What do you think I'm most likely to splurge on?",
  "Finish the sentence: Just by looking at you I'd think ____.",
  "What character would I play in a movie?",
  "Do I remind you of anyone?",
  "Who do you think my celebrity crush is?",
  "Do you think I've ever checked an ex's phone for evidence?",
  "What's the first thing you noticed about me?",
  "What do you think my go to karaoke song is?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "What does my phone wallpaper tell you about me?",
  "Do I look kind? explain.",
  "Do you think I fall in love easily? why or why not?",
  "As a child, what do you think I wanted to be?",
  "Do you think I'm usually early, on time, or late to events? Explain.",
  "What subject do you think I thrived in at school? Did I fail any?",
  "What compliment do you think I hear the most?",
  "Do I seem like a morning person or a night owl? why?",
  "What fast food restaurant do you think I'm most likely to drive through? What's my order?",
  "What is my body language telling you right now?",
  "What does my Instagram tell you about me?",
  "Do you think plants thrive or die in my care? Explain.",
  "On a scale of 1-10, how messy do you think my car is? 1 being cleanest, 10 complete disaster. Explain.",
  "Do you think I was popular in school? explain.",
  "Do you think I've ever been fired from a job? If so, what for?",
  "Do you think I intimidate others? Why or why not?",
  "How likely am I to go camping? How high maintenance is my set up?",
  "What about me is most strange or unfamiliar to you?",
  "What about me intrigues you?",
  "If Myspace were still a thing, what would my profile song be?",

  "Wild Card Maintain eye contact for thirty seconds. What did you notice?",
  "Wild Card Close your eyes. What color is my shirt?",
  "Wild Card Ask and answer the next question in a different accent. (Both players)",
  "Wild Card Draw a picture together. (30 seconds)",
  "Wild Card Write down something others would never guess about you just by looking at you. (Both players) Compare.",
  "Wild Card Draw a portrait of each other to the bst of your ability. (1 minute) Then exchange.",
  "Wild Card Think of your favorite brand of cereal. On the count of three say your answers out loud! (Both players)",
  "Wild Card Think of your favorite childhood tv show of all time. On the count of three, say it out loud! (Both players)",
  "Wild Card On a scale of 1-10, rate your dancing skills. On the count of three, say it out loud! (Both players)",
  "Wild Card Close your eyes. What color are my eyes?",
  "Wild Card Make an assumption about me. (Both players)",
  "Reminder Let go of your attachment to the outcome.",
];

export const level2 = [
  "How can you become a better person?",
  "What's your mother's name? And the most beautiful thing about her?",
  "If you could get to know someone in your life on a deeper level, who would it be and why?",
  "What's the most pain you've ever been in that wasn't physical?",
  "Are you missing anyone right now? Do you think they are missing you too?",
  "What is a dream you've let go of?",
  "What is the last thing you lied to your mother about?",
  "Have you ever told someone I love you but didn't mean it? If so, why?",
  "What are you still trying to prove to yourself?",
  "Are you lying to yourself about anything?",
  "What is your 1st love's name and the reason you fell in love with them?", // Changed him/her to them
  "What part of your life works? What part of your life hurts?",
  "What lesson took you the longest to unlearn?",
  "If you have, when was the moment you realized you weren't invincible?",
  "Do you think the image you have of yourself matches the image people see you as?",
  "If you could have it your way: Who would you be with? Where would you be? And what would you be doing?",
  "Is there a feeling you miss?",
  "What's been your happiest memory this past year?",
  "When was the last time you surprised yourself?",
  "How would you describe the feeling of being in love in one word?",
  "What's your father's name? And tell me one thing about him.",
  "What are you more afraid of, failure or success? And why?",
  "What has been your earliest recollection of happiness?",
  "What do you crave more of?",
  "What is a compliment you wish you received more frequently?",
  "Have you changed your mind about anything recently?",
  "Describe your perfect day!",
  "What is the most unexplainable thing that's ever happened to you?",
  "What would your younger self not believe about your life today?",
  "What is something you wouldn't want to change about yourself?",
  "What title would you give this chapter in your life?",
  "Has a stranger ever changed your life?",
  "How are you, really?",
  "When you're asked how are you, how often do you answer truthfully?",
  "Finish the sentences: strangers would describe me as _____. Only I know that I am ______",
  "What question are you trying to answer most in your life right now?",
  "What's been the best compliment a stranger has ever given you?",

  "Wild Card Staring contest. First to blink must reveal a personal problem and ask your partner for advice on how they might handle it.",
  "Wild Card Ask a question you'd be too afraid to ask. Something you wouldn't dare to ask.",
  "Wild Card Call someone you admire and tell them why you appreciate them! (Put on speaker phone)",
  "Wild Card Admit something.",
  "Wild Card Questions are an art form. Create your own question.",
  "Wild Card Think of something you strongly dislike that most people love. On the count of three, say it out loud! (Both players)",
  "Wild Card Swap seats with your partner.",
  "Wild Card Show the first photo in your camera roll. Explain.",
  "Wild Card Create a secret handshake.",
  "Wild Card Sing the chorus of your favorite song of all time. Get into it!",
  "Wild Card Draw your current mood. Then Compare. (Both players)",
  "Wild Card Both players write an embarrassing fun fact about yourselves. Play a game of rock, paper, scissors. Lost must reveal!",
  "Wild Card Both players write the most important things in life to you. (30 seconds) Compare.",
  "Wild Card Press shuffle on your music library. Explain the first song that comes up!",
  "Reminder Be more interested in understanding others than being understood.",
];

export const level3 = [
  "How would you describe me to a stranger?",
  "What about me surprised you?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "Based on what you learned about me, what book would you recommend I read?",
  "What about me is hardest for you to understand?",
  "What am I most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "If we were in a band, what would our name be?",
  "What can I help you with?",
  "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
  "What do I need to hear right now?",
  "Based on what you know about me, do you have any Netflix recommendations?",
  "What do you think my superpower is?",
  "What is a lesson you will take away from our conversation?",
  "When in this game did you feel most connected to me?",
  "How does one earn your vulnerability? Have I earned it? How can I earn more?",
  "What do you think our most important similarity is?",
  "What can we create together?",
  "In one word, how would you describe our conversation?",
  "What answer of mine made you light up?",
  "When this game is over, what will you remember about me?",
  "What parts of yourself do you see in me?",
  "How do our personalities complement each other?",
  "Why do you think we met?",
  "What do you think my weakness is?",
  "What would make you feel closer to me?",
  "What do you think I fear the most?",
  "What has this conversation taught you about yourself?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "What do you think my defining characterisitic is?",
  "Do you believe everyone has a calling? If so, do you think I've found mine?",
  "What do you recommend I let go of, if anything?",
  "In one word, describe how you feel right now.",

  "Wild Card Give your partner a hug. Not the crappy kind. A ward fluffy one.",
  "Wild Card Write down one thing you want to let go of this year. Read out loud, then rip up together. (Both players)",
  "Wild Card Swap a song suggestion your partner may enjoy. (Both players)",
  "Wild Card Dare your partner to do something outside of their comfort zone in the next week. (Both players)",
  "Wild Card Admit something.",
  "Wild Card Give your partner a compliment you don't think they hear enough.",
  "Wild Card Write a song about your partner. (30 seconds) Then sing it aloud, get into it! (Both players)",
  "Wild Card Scroll through each other's instagrams. Find the picture you feel best represents your partner's essence and comment on why.",
  "Wild Card Both players share somehting you're most grateful for in this current moment.",
  "Wild Card Play a round of rock, paper, scissors. Winner can ask their partner anything. Loser must answer.",
  "Wild Card Give each other nicknames!",
  "Wild Card Create your own question. Make it count.",
  "Wild Card Take a selfie together.",
  "Wild Card Write down a goal for this year. Fold & exchange. Hold each other accountable. (Both players)",
  "Wild Card Both players write a note to your younger selves. (1 minute) Option to compare.",
];

export const finalCard = [
  'Each player write a\n message to the other.\n Fold and exchange.\n Open only once you two\n have parted.'
]